In [1]:
import pandas as pd
import numpy as np

### to store one dimension data using pandas series datastructure

In [2]:
list1=["a","b","c","d","e"]
series1=pd.Series(list1,index=['A','B','C','D','E'])

In [3]:
series1

A    a
B    b
C    c
D    d
E    e
dtype: object

In [4]:
array=np.random.randint(20,25,
size=(9))

In [5]:
array

array([24, 23, 20, 21, 24, 24, 24, 23, 20], dtype=int32)

In [6]:
series2=pd.Series(array)

In [7]:
series2

0    24
1    23
2    20
3    21
4    24
5    24
6    24
7    23
8    20
dtype: int32

In [8]:
series3=pd.Series(np.random.randint(30,35,size=(10)))

In [9]:
series3

0    32
1    33
2    34
3    34
4    34
5    32
6    32
7    33
8    31
9    32
dtype: int32

In [10]:
print(series1,series2,series3)

A    a
B    b
C    c
D    d
E    e
dtype: object 0    24
1    23
2    20
3    21
4    24
5    24
6    24
7    23
8    20
dtype: int32 0    32
1    33
2    34
3    34
4    34
5    32
6    32
7    33
8    31
9    32
dtype: int32

In [11]:
print(series2+series3)

0    56.0
1    56.0
2    54.0
3    55.0
4    58.0
5    56.0
6    56.0
7    56.0
8    51.0
9     NaN
dtype: float64

In [12]:
print(series2-series3)

0    -8.0
1   -10.0
2   -14.0
3   -13.0
4   -10.0
5    -8.0
6    -8.0
7   -10.0
8   -11.0
9     NaN
dtype: float64

In [13]:
print(series2%series3)

0    24.0
1    23.0
2    20.0
3    21.0
4    24.0
5    24.0
6    24.0
7    23.0
8    20.0
9     NaN
dtype: float64

In [14]:
print(series2/series3)

0    0.750000
1    0.696970
2    0.588235
3    0.617647
4    0.705882
5    0.750000
6    0.750000
7    0.696970
8    0.645161
9         NaN
dtype: float64

dataframe

In [15]:
students=["student1",
          "student2",
          "student3",
          "student4",
          "student5"]
rollno=["001",
        "002",
        "003",
        "004",
        "005"]
scores=[45,56,67,89,45]

In [16]:
record={
    "student":students,
    "rollno":rollno,
    "scores":scores
}

In [17]:
record

{'student': ['student1', 'student2', 'student3', 'student4', 'student5'],
 'rollno': ['001', '002', '003', '004', '005'],
 'scores': [45, 56, 67, 89, 45]}

In [18]:
record_df=pd.DataFrame(record)

In [19]:
record_df

    student rollno  scores
0  student1    001      45
1  student2    002      56
2  student3    003      67
3  student4    004      89
4  student5    005      45

In [20]:
record_df.set_index(["rollno","scores"])

                student
rollno scores
001    45      student1
002    56      student2
003    67      student3
004    89      student4
005    45      student5

In [21]:
dict1={
    "A":[1,23,45,67,56],
    "B":[13,45,67,89,70],
    "C":[23,45,77,12,90],
    "D":[34,55,43,56,67],
    "E":[24,56,78,90,45]

}
dict1

{'A': [1, 23, 45, 67, 56],
 'B': [13, 45, 67, 89, 70],
 'C': [23, 45, 77, 12, 90],
 'D': [34, 55, 43, 56, 67],
 'E': [24, 56, 78, 90, 45]}

In [22]:
dict_df=pd.DataFrame(dict1)

In [23]:
dict_df

    A   B   C   D   E
0   1  13  23  34  24
1  23  45  45  55  56
2  45  67  77  43  78
3  67  89  12  56  90
4  56  70  90  67  45

In [24]:
df_1=pd.DataFrame(dict1)

In [25]:
df_1

    A   B   C   D   E
0   1  13  23  34  24
1  23  45  45  55  56
2  45  67  77  43  78
3  67  89  12  56  90
4  56  70  90  67  45

In [26]:
df_1.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [27]:
df_1["A"]

0     1
1    23
2    45
3    67
4    56
Name: A, dtype: int64

In [28]:
df_1["A"]

0     1
1    23
2    45
3    67
4    56
Name: A, dtype: int64

In [29]:
df_1["E"]=df_1["A"]+df_1["B"] +df_1["C"] +df_1["D"]
df_1

    A   B   C   D    E
0   1  13  23  34   71
1  23  45  45  55  168
2  45  67  77  43  232
3  67  89  12  56  224
4  56  70  90  67  283

In [30]:
df_1["F"]=df_1["E"]/4
df_1

    A   B   C   D    E      F
0   1  13  23  34   71  17.75
1  23  45  45  55  168  42.00
2  45  67  77  43  232  58.00
3  67  89  12  56  224  56.00
4  56  70  90  67  283  70.75

### INFO METHOD

In [31]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
 4   E       5 non-null      int64
 5   F       5 non-null      float64
dtypes: float64(1), int64(5)
memory usage: 372.0 bytes

handaling null value

In [32]:
dict2={
    "students":["student1", "student2","student3","student4","student5"],
    "rollno":["001", np.nan,"004","005",np.nan],
    "gender":["male","female","male","female","male"],
    "markss_obtained":[45,67,89,34,56]

}

In [33]:
dict2

{'students': ['student1', 'student2', 'student3', 'student4', 'student5'],
 'rollno': ['001', nan, '004', '005', nan],
 'gender': ['male', 'female', 'male', 'female', 'male'],
 'markss_obtained': [45, 67, 89, 34, 56]}

In [34]:
student_df=pd.DataFrame(dict2)

In [35]:
student_df

   students rollno  gender  markss_obtained
0  student1    001    male               45
1  student2    NaN  female               67
2  student3    004    male               89
3  student4    005  female               34
4  student5    NaN    male               56

to check null alue

In [36]:
student_df.isnull()

   students  rollno  gender  markss_obtained
0     False   False   False            False
1     False    True   False            False
2     False   False   False            False
3     False   False   False            False
4     False    True   False            False

In [37]:
student_df.isna()

   students  rollno  gender  markss_obtained
0     False   False   False            False
1     False    True   False            False
2     False   False   False            False
3     False   False   False            False
4     False    True   False            False

In [38]:
student_df.isnull().sum()

students           0
rollno             2
gender             0
markss_obtained    0
dtype: int64

to check duplicate value in the record

In [39]:
student_df.nunique()

students           5
rollno             3
gender             2
markss_obtained    5
dtype: int64

In [40]:
student_df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [41]:
student_df.duplicated().sum()

np.int64(0)

rmoving duplicate values

In [42]:
student_df.drop_duplicates()

   students rollno  gender  markss_obtained
0  student1    001    male               45
1  student2    NaN  female               67
2  student3    004    male               89
3  student4    005  female               34
4  student5    NaN    male               56

to drop null values

In [43]:
student_df.dropna()

   students rollno  gender  markss_obtained
0  student1    001    male               45
2  student3    004    male               89
3  student4    005  female               34

### mean and mode impuation

In [44]:
student_df

   students rollno  gender  markss_obtained
0  student1    001    male               45
1  student2    NaN  female               67
2  student3    004    male               89
3  student4    005  female               34
4  student5    NaN    male               56

In [45]:
student_df.dropna()

   students rollno  gender  markss_obtained
0  student1    001    male               45
2  student3    004    male               89
3  student4    005  female               34

In [46]:
rollno_mode=student_df['rollno'].mode()

In [47]:
rollno

['001', '002', '003', '004', '005']

In [48]:
gender_mode=student_df['gender'].mode()[0]

In [49]:
gender_mode

'male'

In [50]:
marks_mean=student_df['markss_obtained'].mean()
marks_mean

np.float64(58.2)

In [51]:
student_df['rollno']=student_df['rollno'].fillna(rollno_mode)

In [52]:
student_df['rollno']

0    001
1    004
2    004
3    005
4    NaN
Name: rollno, dtype: object