In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(r"C:\Users\Piyush Deo\Downloads\Titanic-Dataset.csv")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.head(25)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

In [ ]:
df.tail(11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df[["PassengerId","Name","Survived","Sex","Age","Ticket"]].head(5)

,PassengerId,Name,Survived,Sex,Age,Ticket
0,1,"Braund, Mr. Owen Harris",0,male,22.0,A/5 21171
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,PC 17599
2,3,"Heikkinen, Miss. Laina",1,female,26.0,STON/O2. 3101282
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,113803
4,5,"Allen, Mr. William Henry",0,male,35.0,373450

In [ ]:
df.loc[4:10,"Name":"Parch"]

,Name,Sex,Age,SibSp,Parch
4,"Allen, Mr. William Henry",male,35.0,0,0
5,"Moran, Mr. James",male,NaN,0,0
6,"McCarthy, Mr. Timothy J",male,54.0,0,0
7,"Palsson, Master. Gosta Leonard",male,2.0,3,1
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0
10,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1

In [ ]:
df.iloc[15:26,2:8]

,Pclass,Name,Sex,Age,SibSp,Parch
15,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0
16,3,"Rice, Master. Eugene",male,2.0,4,1
17,2,"Williams, Mr. Charles Eugene",male,NaN,0,0
18,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0
19,3,"Masselmani, Mrs. Fatima",female,NaN,0,0
20,2,"Fynney, Mr. Joseph J",male,35.0,0,0
21,2,"Beesley, Mr. Lawrence",male,34.0,0,0
22,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0
23,1,"Sloper, Mr. William Thompson",male,28.0,0,0
24,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1
25,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5

In [ ]:
df[["Name","Sex"]]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
283,284,1,3,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S
266,267,0,3,"Panula, Mr. Ernesti Arvid",male,16.0,4,1,3101295,39.6875,NaN,S
225,226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22.0,0,0,PP 4348,9.3500,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
age_mean=df["Age"].mean()
age_mean=np.round(age_mean,2)
age_mean

np.float64(29.7)

In [ ]:
embarked_mode=df["Embarked"].mode()[0]
embarked_mode

'S'

In [ ]:
df["Age"]=df["Age"].fillna(age_mean)
df["Embarked"]=df["Embarked"].fillna(embarked_mode)

In [ ]:
df["Age"]
df["Embarked"]

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [ ]:

removing_column=df["Name"]

In [ ]:
removing_column

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
def fare_category(Fare):
    if Fare<15:
        return"Low"
    elif Fare<40:
        return"Medium"
    else:
        return"High"

In [ ]:
df["fare_category"]=df["Fare"].apply(fare_category)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Low

In [ ]:
df=df.drop(columns=["fare_category"])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df["Cabin"].values

array([nan, 'C85', nan, 'C123', nan, nan, 'E46', nan, nan, nan, 'G6',
       'C103', nan, nan, nan, nan, nan, nan, nan, nan, nan, 'D56', nan,
       'A6', nan, nan, nan, 'C23 C25 C27', nan, nan, nan, 'B78', nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'D33', nan, 'B30', 'C52', nan, nan, nan,
       nan, nan, 'B28', 'C83', nan, nan, nan, 'F33', nan, nan, nan, nan,
       nan, nan, nan, nan, 'F G73', nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'C23 C25 C27', nan, nan, nan, 'E31', nan,
       nan, nan, 'A5', 'D10 D12', nan, nan, nan, nan, 'D26', nan, nan,
       nan, nan, nan, nan, nan, 'C110', nan, nan, nan, nan, nan, nan, nan,
       'B58 B60', nan, nan, nan, nan, 'E101', 'D26', nan, nan, nan,
       'F E69', nan, nan, nan, nan, nan, nan, nan, 'D47', 'C123', nan,
       'B86', nan, nan, nan, nan, nan, nan, nan, nan, 'F2', nan, nan,
       'C2', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, 'E33', nan, nan, nan, 'B19', nan, nan, nan, 'A7', nan,
       nan, 'C49', nan, nan, nan, nan, nan, 'F4', nan, 'A32', nan, nan,
       nan, nan, nan, nan, nan, 'F2', 'B4', 'B80', nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'G6', nan, nan, nan, 'A31', nan, nan, nan,
       nan, nan, 'D36', nan, nan, 'D15', nan, nan, nan, nan, nan, 'C93',
       nan, nan, nan, nan, nan, 'C83', nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, 'C78', nan, nan, 'D35', nan,
       nan, 'G6', 'C87', nan, nan, nan, nan, 'B77', nan, nan, nan, nan,
       'E67', 'B94', nan, nan, nan, nan, 'C125', 'C99', nan, nan, nan,
       'C118', nan, 'D7', nan, nan, nan, nan, nan, nan, nan, nan, 'A19',
       nan, nan, nan, nan, nan, nan, 'B49', 'D', nan, nan, nan, nan,
       'C22 C26', 'C106', 'B58 B60', nan, nan, nan, 'E101', nan,
       'C22 C26', nan, 'C65', nan, 'E36', 'C54', 'B57 B59 B63 B66', nan,
       nan, nan, nan, nan, nan, 'C7', 'E34', nan, nan, nan, nan, nan,
       'C32', nan, 'D', nan, 'B18', nan, 'C124', 'C91', nan, nan, nan,
       'C2', 'E40', nan, 'T', 'F2', 'C23 C25 C27', nan, nan, nan, 'F33',
       nan, nan, nan, nan, nan, 'C128', nan, nan, nan, nan, 'E33', nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 'D37', nan, nan, 'B35',
       'E50', nan, nan, nan, nan, nan, nan, 'C82', nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 'B96 B98', nan, nan, 'D36',
       'G6', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'C78', nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, 'E10', 'C52', nan,
       nan, nan, 'E44', 'B96 B98', nan, nan, 'C23 C25 C27', nan, nan, nan,
       nan, nan, nan, 'A34', nan, nan, nan, 'C104', nan, nan, 'C111',
       'C92', nan, nan, 'E38', 'D21', nan, nan, 'E12', nan, 'E63', nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, 'D', nan, 'A14', nan,
       nan, nan, nan, nan, nan, nan, nan, 'B49', nan, 'C93', 'B37', nan,
       nan, nan, nan, 'C30', nan, nan, nan, 'D20', nan, 'C22 C26', nan,
       nan, nan, nan, nan, 'B79', 'C65', nan, nan, nan, nan, nan, nan,
       'E25', nan, nan, 'D46', 'F33', nan, nan, nan, 'B73', nan, nan,
       'B18', nan, nan, nan, 'C95', nan, nan, nan, nan, nan, nan, nan,
       nan, 'B38', nan, nan, 'B39', 'B22', nan, nan, nan, 'C86', nan, nan,
       nan, nan, nan, 'C70', nan, nan, nan, nan, nan, 'A16', nan, 'E67',
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'C101',
       'E25', nan, nan, nan, nan, 'E44', nan, nan, nan, 'C68', nan, 'A10',
       nan, 'E68', nan, 'B41', nan, nan, nan, 'D20', nan, nan, nan, nan,
       nan, nan, nan, 'A20', nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'C125', nan, nan, nan, nan, nan, nan, nan, nan, 'F4', nan, nan,
       'D19', nan, nan, nan, 'D50', nan, 'D9', nan, nan, 'A23', nan,
       'B50', nan, nan, nan, nan, nan, nan, nan, nan, 'B35', nan, nan,
       nan, 'D33', nan, 'A26', nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, 'D48', nan, nan, 'E58', nan, nan, nan, nan, nan,
       nan, 'C126', nan, 'B71', nan, nan, nan, nan, nan, nan, nan,
       'B51 B53 B55', nan, 'D49', nan, nan, nan, nan, nan, nan, nan, 'B5',
       'B20', nan, nan, nan, nan, nan, nan, nan, 'C68', 'F G63',
       'C62 C64', 'E24', nan, nan, nan, nan, nan, 'E24', nan, nan, 'C90',
       'C124', 'C126', nan, nan, 'F G73', 'C45', 'E101', nan, nan, nan,
       nan, nan, nan, 'E8', nan, nan, nan, nan, nan, 'B5', nan, nan, nan,
       nan, nan, nan, 'B101', nan, nan, 'D45', 'C46', 'B57 B59 B63 B66',
       nan, nan, 'B22', nan, nan, 'D30', nan, nan, 'E121', nan, nan, nan,
       nan, nan, nan, nan, 'B77', nan, nan, nan, 'B96 B98', nan, 'D11',
       nan, nan, nan, nan, nan, nan, 'E77', nan, nan, nan, 'F38', nan,
       nan, 'B3', nan, 'B20', 'D6', nan, nan, nan, nan, nan, nan,
       'B82 B84', nan, nan, nan, nan, nan, nan, 'D17', nan, nan, nan, nan,
       nan, 'B96 B98', nan, nan, nan, 'A36', nan, nan, 'E8', nan, nan,
       nan, nan, nan, 'B102', nan, nan, nan, nan, 'B69', nan, nan, 'E121',
       nan, nan, nan, nan, nan, 'B28', nan, nan, nan, nan, nan, 'E49',
       nan, nan, nan, 'C47', nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'C92', nan, nan, nan, 'D28', nan, nan, nan, 'E17', nan, nan, nan,
       nan, 'D17', nan, nan, nan, nan, 'A24', nan, nan, nan, 'D35',
       'B51 B53 B55', nan, nan, nan, nan, nan, nan, 'C50', nan, nan, nan,
       nan, nan, nan, nan, 'B42', nan, 'C148', nan], dtype=object)

handling the null vaLUE in the cabin filling'yes' in tyhe passenger having cabin otherwise 'no'.if nan

In [ ]:
df["Has_Cabin"]=np.where(df["Cabin"].notna(),"Yes","No")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Has_Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,No
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,No
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,No

#now remove the cabin column from the dataframe

In [ ]:
df=df.drop(columns=["Cabin"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Has_Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,No
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,No
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,No
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,No
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Yes
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,S,No
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Yes
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,No

In [ ]:
df["Has_Cabin"]=df["Has_Cabin"].map({"Yes":1,"No":0})
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Has_Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0

In [ ]:
cleaned_df=df.copy()
cleaned_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Has_Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

In [ ]:
cleaned_df.to_csv("cleaned_titanic_dataset.csv")